name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Build'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Hydroper RB tool
        run: npm i -g com.hydroper.rb
      - name: Build reference portal
        run: hydroper-rb build
      - name: Git commit report
        run: |
          mv -f out/* .
          rm -rf out

          # Git commit
          git config --global user.name 'hydroperfox'
          git config --global user.email 'hydroperfox@gmail.com'
          git switch -C ghpages
          git rm -r .github src theme .gitignore book.toml
          git add .
          git commit -m "Automated report"
          git push origin -f ghpages
